Document: java2script
Title: Debian java2script Manual
Author: <insert document author here>
Abstract: This manual describes what java2script is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/java2script/java2script.sgml.gz

Format: postscript
Files: /usr/share/doc/java2script/java2script.ps.gz

Format: text
Files: /usr/share/doc/java2script/java2script.text.gz

Format: HTML
Index: /usr/share/doc/java2script/html/index.html
Files: /usr/share/doc/java2script/html/*.html
